version: "2"
linters:
  settings:
    revive:
      severity: warning
      rules:
        - name: argument-limit
          arguments:
            - 5
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - "^third_party/"
      - "^builtin/"
      - "^examples/"
      - "^tests/"
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
