name: Pull Request CI

on:
  pull_request:
    branches:
      - develop
      - "release/**"
    paths-ignore:
      - "*.md"
      - "BUILDMETA"
      - "changelogs/**"
      - "docs/**"
      - "design/**"
      - "LICENSE"
      - "MAINTAINERS"
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      branch-name: ${{ github.event.pull_request.base.ref }}
      action-name: ${{ github.event_name }}
      
  tests:
    needs: ["lint"]
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  csi-driver:
    runs-on: ubuntu-latest
    needs: ["lint"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./buildscripts/lvm-driver/Dockerfile.buildx
          push: false
          platforms: linux/amd64, linux/arm64
